"""create exchange_rate_history table

Revision ID: 8e4221b7af4e
Revises: 
Create Date: 2026-09-27 16:36:04.330655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4221b7af4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', 'rate_date', 'provider', name='uq_rate_history_pair_date_provider')
    )
    op.create_index(op.f('ix_exchange_rate_history_base_currency'), 'exchange_rate_history', ['base_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rate_history_rate_date'), 'exchange_rate_history', ['rate_date'], unique=False)
    op.create_index(op.f('ix_exchange_rate_history_target_currency'), 'exchange_rate_history', ['target_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rate_history_target_currency'), table_name='exchange_rate_history')
    op.drop_index(op.f('ix_exchange_rate_history_rate_date'), table_name='exchange_rate_history')
    op.drop_index(op.f('ix_exchange_rate_history_base_currency'), table_name='exchange_rate_history')
    op.drop_table('exchange_rate_history')
    # ### end Alembic commands ###
